### ISSUE TITLE
`date_spine` no longer works on BigQuery

### ISSUE THREAD

**Issue by dolfth** [dbt-labs/dbt-utils#120]
Using date_spine this way on BigQuery

`    {{ dbt_utils.date_spine(
        "day",
        "parse_date('%F', '2000-01-01')",
        "date_add(current_datetime, interval 53 week)"
       )
    }}
`
errors with the following message:
`No matching signature for operator <= for argument types: DATETIME, DATE. Supported signatures: ANY <= ANY`
It seems that the errors results from the comparison in [this line](https://github.com/fishtown-analytics/dbt-utils/blob/ce8daeb6e01490f2833b8cd6cb06656b891f667b/macros/datetime/date_spine.sql#L63) that refers to dateadd. Looking at that file it seems that [this commit to dateadd](https://github.com/fishtown-analytics/dbt-utils/commit/eefa8441ac484f47e332c22f316379038f72af41) changed the type of the output of the macro to datetime in the case of BQ. Reverting to the older version solves the problem.

**Comment by drewbanin** [comment]
hey @dolfth - thanks for the report. Just wanted to acknowledge that I saw this - will take a look this week!

**Comment by dolfth** [comment]
I am currently working with [this version of date_add](https://github.com/fishtown-analytics/dbt-utils/blob/29050eec54ac044e96c4c0151b24d8cf4386fbac/macros/cross_db_utils/dateadd.sql) without any problems

**Comment by drewbanin** [comment]
thanks for the update!

**Comment by clausherther** [comment]
Hi, just wanted to check on this. Any plans to merge @dolfth's version of date_add to make the date_spine work?

**Comment by clausherther** [comment]
Ah, looks like I have to call the date_spine macro like this
```
{{ dbt_utils.date_spine(
        datepart="day",
        start_date="cast('" ~ start_date ~ "' as datetime)",
        end_date="cast('" ~ end_date ~ "' as datetime)",
       )
    }}
```
since the `day_date column` is of type `datetime` instead of `date`.

**Comment by jtcohen6** [comment]
Hey folks! I know this issue is from a while ago. I was able to get `date_spine` working on BQ with a _very_ slight tweak to @dolfth's original code:
```sql
{{ dbt_utils.date_spine( "day", "parse_date('%F', '2000-01-01')", "datetime_add(current_datetime, interval 53 week)" ) }}
```
As @clausherther notes, the BQ implementation of `dbt_utils.dateadd` returns a `datetime` rather than a `date`, so the `end_date` needs to be of type `datetime`. The datatype of `start_date` doesn't appear to matter as long as it's one of `date`, `datetime`, `timestamp`.

I think it would make sense to (a) try to make the macro more flexible by safe-casting to `datetime` in [this line](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/datetime/date_spine.sql#L63), or (b) specify in the README that the `end_date` expression must return a `datetime`.

Thoughts?

**Comment by clausherther** [comment]
I like the idea of safe-casting inside the macro. That would allow folks to port older code from something like Redshift to BQ more easily. If you don't already have a PR on this @jtcohen6 I'll take a stab.
