### ISSUE TITLE
current_timestamp -- defined dbt-utils and within adapter themselves?

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-utils#339]
I'm sure there's a reason, but why is `current_timestamp()` getting redefined here? From what I can tell the macro already lives in the plugins' `adapters.sql`

https://github.com/fishtown-analytics/dbt-utils/blob/c64b52068070023bc3524525e06a14ad72d485a4/macros/cross_db_utils/current_timestamp.sql#L1-L15

**Comment by jtcohen6** [comment]
The reason is that `dbt_utils.current_timestamp()` (August 2017, https://github.com/fishtown-analytics/dbt-utils/commit/b8da01ac990a1d0be439cdd57e8ccb864acd1597) predates `dbt.current_timestamp` (Feb 2019, https://github.com/fishtown-analytics/dbt/pull/1272, i.e. source freshness). This happens every now and again, whereby we've upstreamed some utility macros as necessary prerequisites for core dbt functionality.

I think it would make a lot of sense to PR this package and make `dbt_utils.current_timestamp` no more than a wrapper around the in-adapter version, something like:
```sql
{% macro current_timestamp() -%}
  {{ return(adapter.dispatch('current_timestamp', packages = dbt_utils._get_utils_namespaces())()) }}
{%- endmacro %}

{% macro default__current_timestamp() %}
   {{ return(dbt.current_timestamp()) }}
{% endmacro %}
```

**Comment by dbeatty10** [comment]
As always, you have the all-seeing eye 👁️  @dataders 

Closing in favor of https://github.com/dbt-labs/dbt-core/issues/5521
