### ISSUE TITLE
Create zero_pad_timestamp_ms() macro to work around Snowflake and Redshift producing different results in surrogate_key()

### ISSUE THREAD

**Issue by sphinks** [dbt-labs/dbt-utils#408]
### Describe the bug
Due to internal mechanics Redshift and Snowflake could produce different surrogate keys on the same data sets. It is very confusing in case you are doing migration or somehow use both of databases. The main issue are connected with casting of timestamp fields. It implements in really strange way in Redshift. As an example:

Input:
```
select
    cast(TIMESTAMP '2021-03-19 17:07:10.123321' as varchar),
    cast(TIMESTAMP '2021-03-19 17:07:10.123000' as varchar),
    cast(TIMESTAMP '2021-03-19 17:07:10.100000' as varchar),
    cast(TIMESTAMP '2021-03-19 17:07:10.000000' as varchar);
```
Output Redshift:
```
2021-03-19 17:07:10.123321,
2021-03-19 17:07:10.123,
2021-03-19 17:07:10.10,
2021-03-19 17:07:10
```
Output Snowflake:
```
2021-03-19 17:07:10.123321,
2021-03-19 17:07:10.123000,
2021-03-19 17:07:10.100000,
2021-03-19 17:07:10.000000
```
### Steps To Reproduce
Just use dbt https://github.com/dbt-labs/dbt-utils#surrogate_key-source on any value with timestamp.

### Expected behavior
I suppose it is better in case surrogate key will produce the same output with any database adapter and will be agnostic to database engine.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ x] redshift
- [ ] bigquery
- [ x] snowflake
- [ ] other (specify: ____________)

### Additional context
I'm not sure if I should put the issue into bug section or in feature one. I also not sure if the issues affect a lot of people, may be it no so nessesary to fix. However, in case you faced the issues it will require enormous amount of efforts to fix.

P.S. I could to fix the issue for Redshift adapter to let it produce the same expected output. Just point me where to start.

**Comment by joellabes** [comment]
Hey @sphinks, thanks for writing this up! 

I agree with @jtcohen6 that ideally you should get the same results, regardless of the adapter you’re using. 

I am curious as to which of Snowflake and Redshift is the outlier from the other core adapters, as that will impact which behaviour we change. I'll do some digging internally - we should have one of every type of database lying around 🤞 

Regardless, given that people don't switch databases _that_ often compared to the likelihood that they want their existing surrogate keys to keep working, I think this will need to be an opt-in behaviour. That might look like a new argument to the macro, or an entirely separate macro. 

- New projects can comfortably use the new method
- Existing projects should keep the old method for existing keys and consider switching for new ones. 

|              |  generate new key | generate existing key |   
|--------------|-------------|------------------|
| new project      | new method        | -              |  
| existing project | new method (probably)           | old method             |

Right now, the main focus of dbt-utils development is to support migration to dbt Core 1.0 later this year. This feels like a tricky enough change and enough of an edge case that we won't want to drop it on users and impact their ability to upgrade to 1.0, so it'll be down the priority list for a while.

**Comment by joellabes** [comment]
I did some digging!

## BigQuery
BQ uses the `string` type, and the code
```
select cast(TIMESTAMP '2021-03-19 17:07:10.123321' as string ) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.123000' as string) union all 
select cast(TIMESTAMP '2021-03-19 17:07:10.100000' as string) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.000000' as string)
```

returns 
```
2021-03-19 17:07:10.123321+00 
2021-03-19 17:07:10.123+00   
2021-03-19 17:07:10.100+00 
2021-03-19 17:07:10+00
```

Interesting points:
- there's a `+00` suffix
- 1 and 3 significant figures after the decimal both result in 3dp of precision (123 and 100)
- 0 sig figs leads to no decimal at all 

## Snowflake
Varchars behave as described above. 

```
select cast(TIMESTAMP '2021-03-19 17:07:10.123321' as varchar) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.123000' as varchar) union all 
select cast(TIMESTAMP '2021-03-19 17:07:10.100000' as varchar) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.000000' as varchar)
```

returns 6dp of precision no matter what:
```
2021-03-19 17:07:10.123321
2021-03-19 17:07:10.123000
2021-03-19 17:07:10.100000
2021-03-19 17:07:10.000000
```

When casting to a `string`, 

```
select cast(TIMESTAMP '2021-03-19 17:07:10.123321' as string) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.123000' as string) union all 
select cast(TIMESTAMP '2021-03-19 17:07:10.100000' as string) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.000000' as string)
```
You get a fixed 3dp of precision:
```
2021-03-19 17:07:10.123
2021-03-19 17:07:10.123
2021-03-19 17:07:10.100
2021-03-19 17:07:10.000
```

## Redshift and Postgres
Behave identically, as described above for Redshift

```
select cast(TIMESTAMP '2021-03-19 17:07:10.123321' as varchar) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.123000' as varchar) union all 
select cast(TIMESTAMP '2021-03-19 17:07:10.100000' as varchar) union all
select cast(TIMESTAMP '2021-03-19 17:07:10.000000' as varchar)
```

Returns 

```
2021-03-19 17:07:10.123321
2021-03-19 17:07:10.123
2021-03-19 17:07:10.10
2021-03-19 17:07:10
```

## What to do?
Since there is no consistency between the three cloud DWHs, I think the compatibility mode should zero-pad the strings to be consistent with Snowflake's format. Obviously when there is no decimal place, that will need to be added. 

To solve this for users who are concerned about cross-db compatibility, a contributor might like to make a new macro along the lines of `zero_pad_timestamp_ms()`, or `timestamp_as_string()`. By doing that, we'd get a consistent input to the surrogate key macro, but wouldn't have to worry about backwards compatibility. 

This approach solves another problem I just realised: if there wasn't another wrapper macro, I don't actually know how we'd know that it was a timestamp in need of reformatting, as opposed to some other data type.

**Comment by joellabes** [comment]
I've removed the 1.0 label, because this can be handled at any time without causing backwards-compatibility issues. The new macro `zero_pad_timestamp_ms()` can be added into any new surrogate key implementations, when people know that cross-database compatibility is important to them. 

Old: 
`{{ dbt_utils.surrogate_key(['user_id', 'account_created_at']) }}`

New:
`{{ dbt_utils.surrogate_key(['user_id', zero_pad_timestamp_ms('account_created_at')]) }}`

My only questions now is whether this new macro belongs in dbt_utils, or whether we punt it back to the adapters to conform to an expected implementation defined in Core. @jtcohen6 and @dbeatty10, what say you?

**Comment by jtcohen6** [comment]
I buy this as a cross-db macro that lives in `dbt-core` (default: do nothing?), and only needs implementations on adapters for data platforms that do not here to our expected standard

**Comment by joellabes** [comment]
> default: do nothing

it should still return a string, so I guess it can just be `cast({{ column }} as {{ type_string() }})` but yeah basically nothing!
