### ISSUE TITLE
Quoting issue: dbt assumes the column not to be reserved word

### ISSUE THREAD

**Issue by pankajsaini-ldt** [dbt-labs/dbt-utils#427]
https://github.com/dbt-labs/dbt-utils/blob/fc180464bd8a2b58d18810e535e4ac96da61e850/macros/sql/get_column_values.sql#L32

Steps to reproduce:

`{{ dbt_utils.get_column_values(source('<source>', '<table_name>') ,'<any_sql_reserved_word>') }}`

**Comment by joellabes** [comment]
Hi @pankajsaini-ldt, it should work if you pass your column name in double quoted (i.e. `'` and `"`): 

`{{ dbt_utils.get_column_values(source('<source>', '<table_name>') ,'"select"') }}`

The reason is that the first set of quotes going into Jinja are to tell _Jinja_ that it's a string, not SQL. The second set would be passed through, so you'd get `"select" as value`
