### ISSUE TITLE
get sources by prefix

### ISSUE THREAD

**Issue by joeyfezster** [dbt-labs/dbt-utils#434]
### Describe the feature
Much like [`get_relations_by_prefix`](https://github.com/dbt-labs/dbt-utils#get_relations_by_prefix-source) returns a list of tables, `get_sources_by_prefix` would return a list of sources.

### Describe alternatives you've considered
[This slack thread](https://getdbt.slack.com/archives/C2JRRQDTL/p1628285076174000) discusses potential alternatives, though no clear solution is found other than manual hardcoding of the sources.

### Who will this benefit?
This is especially helpful when raw data is periodically added (and somehow marked as a source by some separate automated process), and then joined - think concatenating tables into one.

**Comment by joellabes** [comment]
Hey @joeyfezster, welcome to the club of people who would like to see this sort of thing improved! 

There's a handful of existing issues in the dbt core repo that touch on this. For example, I think you have a similar use case as I describe in https://github.com/dbt-labs/dbt-core/issues/3862, when I was using dbt at my old job. 

If I'm understanding, I think we would be covered if https://github.com/dbt-labs/dbt-core/issues/3072 was implemented, so that the `graph.sources` object is populated when the project is parsed. 

(While we're pulling out greatest hits, https://github.com/dbt-labs/dbt-core/issues/1212 asks for dynamic _model_ referencing, not sources.)

dbt-utils makes it easier to do things that are already possible in dbt-core by adding abstractions and syntactic sugar. Since this isn't possible in Core yet, I'm going to close this issue but I encourage you to go and re-open the conversation on https://github.com/dbt-labs/dbt-core/issues/3072 in particular. It only closed because it went stale, there's still broad interest in seeing it happen!
