### ISSUE TITLE
dbt_utils.star requires uppercase field names, unlike documentation suggests

### ISSUE THREAD

**Issue by TheChrisWoodard** [dbt-labs/dbt-utils#515]
### Describe the bug

While working with` dbt_utils.star(..., except = [ ])`, I spent an hour and ran into error after error before realizing that the fields to be excluded should be uppercase rather than lowercase. The documentation provided [here](https://hub.getdbt.com/dbt-labs/dbt_utils/latest/) and screenshotted below was deceiving, as the text for `"exclude_field_1",` etc. was lowercase. Maybe an experienced dbt user would have known this already but it was a real headache for a beginner like me. 

A helpful update that could prevent future users from getting hung up on this would be to list fields in the documentation in all caps, not only for dbt_utils.star but for other Jinja tools and SQL generators that take fields as inputs.

### Steps to reproduce
Leave any column in the `except` clause lowercase. 

### Expected results

`{{ dbt_utils.star(from=ref('XXX'), except=["field_1","field_2"]) }}`
Expected field_1 and field_2 would be removed. 

### Actual results

field_1 and field_2 remained. 

### Screenshots and log output

![image](https://user-images.githubusercontent.com/77743691/157747646-07c362fc-cb54-4e84-b82f-f998645b407f.png)

### System information
**The contents of your `packages.yml` file:**

packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.3

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt 1.0.3
dbt-snowflake 0.19.1
```

### Are you interested in contributing the fix?
Sure, if I can gain permission to contribute.

**Comment by joellabes** [comment]
Hi @TheChrisWoodard, sorry you ran into trouble here! I agree that this is a pain. 

As with all good issues, ✨ it depends ✨  - because Snowflake is so pedantic about its column casing, where other databases aren't, in most cases a lowercase example would actually work. 

Not so much in your case though, and this did actually bite me a few weeks ago so I empathise 😢 

I would be happy to see a PR that improved the documentation by clarifying that the arguments are case sensitive - see https://docs.github.com/en/get-started/quickstart/contributing-to-projects for more info about how to fork the project, make your changes, and open a pull request to contribute them back to the main repository. Let me know if you run into any problems with this though - the first contribution is always fiddly because it comes with a bunch of one-time setup overhead.

**Comment by joellabes** [comment]
@TheChrisWoodard it turns out that this is already supported in the most recent versions of dbt_utils: 
https://github.com/dbt-labs/dbt-utils/blob/5717b109d358844e0f085565b93e74cbe469ecb0/macros/sql/star.sql#L16-L20

I recommend you update your packages.yml to one of the following: 
```yaml
- package: dbt-labs/dbt_utils
   version: 0.7.6 # if you're not on dbt v1.0 yet
```

```yaml
- package: dbt-labs/dbt_utils
   version: [">=0.8.0", "<0.9.0"] # better, if you're already on dbt 1.0
```

Note in particular that the organisation name has changed from `fishtown-analytics` to `dbt-labs`.
