### ISSUE TITLE
Default implementation of `deduplicate` is not null-safe

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-utils#621]
### Describe the bug
@belasobral93 discovered that `deduplicate` doesn't work for Spark when any of the `order_by` columns are `null`.

#### Root cause
The root cause is that [Spark defaults to `NULLS FIRST` for the null_sort_order](https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-orderby.html#parameters) for the `ORDER BY` clause.

#### Why `dbt_utils` rather than `spark_utils`?

<details>
  <summary>Explanation</summary>

> But `dbt_utils` doesn't officially support Spark, so why is this being reported here (instead of `spark_utils`)?

`dbt_utils` is providing [five implementations for `deduplicate`](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/deduplicate.sql):
1. default
2. redshift
3. postgres
4. snowflake
5. bigquery

Since `dbt_utils` only tests against the four databases listed above and each of those has an override, it means there is **no testing** for the `default` implementation which the other dbt adapters inherit (like Spark).

</details>

### Steps to reproduce
<details>
  <summary>SQL example</summary>

The current implementation essentially acts like the following example:
```sql
with relation as (

    select 1 as partition_by, 'a' as order_by
    union all
    select 1 as partition_by, 'a' as order_by
    union all
    select 2 as partition_by, 'a' as order_by
    union all
    select 2 as partition_by, 'b' as order_by
    union all
    select 2 as partition_by, NULL as order_by

),

row_numbered as (

    select
        _inner.*,
        row_number() over (
            partition by partition_by
            order by order_by
        ) as rn
    from relation as _inner

)

select
    distinct relation.*
from relation
natural join row_numbered
where row_numbered.rn = 1
;
```

</details>

### Expected results
| partition_by | order_by |
|--------------|----------|
| 1            | a        |
| 2            | a        |

### Actual results
| partition_by | order_by |
|--------------|----------|
| 1            | a        |

### Screenshots and log output
Not provided.

### System information
Not provided.

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other: spark

**The output of `dbt --version`:**
Not provided.

### Additional context
To make the fix, it might be as simple as:
- adding `nulls last` after `order_by` (when an `order by` clause exists, of course)

To confirm the bug and establish sufficient test cases, we could:
1. comment out all adapter-specific overrides for `deduplicate`
1. re-run the test suite
1. add test cases as needed
1. re-run the test suite
1. make fixes to the implementation(s)
1. re-run the test suite

### Are you interested in contributing the fix?
I will contribute the fix.

**Comment by joellabes** [comment]
> To make the fix, it might be as simple as:
> 
> * adding `nulls last` after `order_by` (when an `order by` clause exists, of course)

Is `nulls [last|first]` a well-known part of the SQL spec? I've never heard of it, a bit of quick Googling implies that it's [specific-ish](https://en.wikipedia.org/wiki/Order_by#cite_note-sqlitenulls-1:~:text=SQL%3A2003%20extension-,T611,-%2C%20%22Elementary%20OLAP%20operations)

A couple of things that are only in my head/true by convention but not documented:
- Deviations from the norm (`default__` implementations) should be handled in an override. (Strongly held)
- "The norm" is vanilla-flavoured things that can reasonably be expected of pretty much everything. <sup>1</sup> (Pretty strongly held)
- I tend to assume that Postgres is vanilla-flavoured, as the longest-lived and only-OSS DB in the original core four. (Not at all strongly held, but don't have a better idea)
<sup>1</sup> Lookin' at you, BigQuery types

The approach that would be truest to points 1 and 3 would be: 
- The `default` implementation changes to Postgres' 
- Anyone who can't do that builds their own

Which is right if we want a globally coherent and understandable set of principles. It's not super pragmatic though; it appears that [10](https://github.com/dbt-labs/dbt-utils/blob/064c2abee80816ea855de32e66e54e96d9916677/macros/sql/deduplicate.sql#L57-L58) data platforms support our current implementation, and as far as I can see most of them would not support Postgres' because they don't have `distinct on`. 

In my opinion, "Vanilla as default" is more important than "every default implementation is what would work best in Postgres". (In fact, this might be a case where the default implementation _works_ on PGSQL, but there is a [special optimisation](https://github.com/dbt-labs/dbt-utils/discussions/590#discussioncomment-2766961) that led to the custom version? I haven't checked). 

So that's a lot of words to say that if [MySQL, Redshift, Materialize, SingleStore](https://github.com/dbt-labs/dbt-utils/blob/064c2abee80816ea855de32e66e54e96d9916677/macros/sql/deduplicate.sql#L57-L58) don't understand `nulls last` then we are inconveniencing some new adapters by throwing it in, and maybe we're better off just specifying `nulls last` in the Spark version.

**Comment by joellabes** [comment]
Related (in that it's also a deduplicate issue): https://github.com/dbt-labs/dbt-utils/issues/713

**Comment by nitindatta** [comment]
anyone any workarounds for this
