### ISSUE TITLE
Have compare_columns support BigQuery Arrays for equality test

### ISSUE THREAD

**Issue by jasonqng** [dbt-labs/dbt-utils#635]
### Describe the feature
We would like to use the [db_utils `compare_columns`](https://github.com/dbt-labs/dbt-utils#equality-source) to be able to check BigQuery clolumns with arrays in tests. At the moment, it does not appear to be supported.

### Describe alternatives you've considered
Alternatives are to not use dbt to test for equality of arrays, and instead to test it via API call and comparing the results in Python, which requires extra work.

### Additional context
BigQuery arrays are our use case, but I imagine this problem for any db with arrays and the solution might be generalizable to others.

### Who will this benefit?
Any who writes tests and has databases with arrays.

### Are you interested in contributing this feature?
Sure, I'd love to take a crack at this if someone points me in the right direction. I see the code here https://github.com/dbt-labs/dbt-utils/blob/37199d3901a97e813899dc25c1f72601714c2c3c/macros/generic_tests/equality.sql. It looks pretty straightforward, just have to support either user supplying a flag or maybe the datatype of the column being an array is inferred. Once there, then it's a matter of just flattening the column/table (in BigQuery, with UNNEST, other dialects, not sure, hence, maybe this is a BQ specific solution?)

**Comment by joellabes** [comment]
I think I'm on board with this!

Off the top of my head, I'm pretty sure that this line https://github.com/dbt-labs/dbt-utils/blob/37199d3901a97e813899dc25c1f72601714c2c3c/macros/generic_tests/equality.sql#L32 

will get you kicked off nicely. `get_columns_in_relation` returns a [Column](https://docs.getdbt.com/reference/dbt-classes#column) object, which has a `data_type` property. You should be able to look at that to know if it's an array (I don't know all the different names of arrays on the different warehouses, but Murphy's law states that they aren't all the same 😭) and then you can unnest accordingly. You'll want to stop extracting just the `quoted` field because you're now going to need `quoted` and `data_type`. 

Note also the special BigQuery type on that same page. 

This wouldn't work for ephemeral models; I think I'm OK with that! I certainly wouldn't want to be passing in the names of which columns are arrays and which ones are more vanilla datatypes, which means we have to work it out from the adapter method above. 

Does that get you pointed in the right direction?

**Comment by jasonqng** [comment]
@joellabes Thanks for the pointers. I'll take a crack at it later this week. I'll probably need your help with tests and/or other polish, but hopefully I can at least get a prototype PR working for you all to look at.

**Comment by pishposh** [comment]
@jasonqng If you’ve made any progress on this, I’d love to take a look as well!

I was thinking about contributing a patch that would handle both struct and array fields, using `TO_JSON_STRING()` to serialize them into a format BQ can compare directly. It looks like BQ preserves field order when serializing structs, and BQ arrays are ordered, so this seems relatively safe and easy to me. Dumping field value diffs as JSON would work for my own immediate use case, but it seems like this could be finessed. Any thoughts about this?

**Comment by joellabes** [comment]
I actually really like that workaround! If it is documented anywhere that serialisation to strings happens in a deterministic, repeatable fashion then that feels like a low-drama way to handle this.

**Comment by jasonqng** [comment]
@pishposh Haven't had a chance to do so, and yeah, handling structs would be amazing too. Go for it! Look forward to helping to test and review if helpful!
