### ISSUE TITLE
Union.sql Faulty For Table Name With Special Characters

### ISSUE THREAD

**Issue by CharlieJ20** [dbt-labs/dbt-utils#649]
### Describe the bug
I was unioning two table names with union.sql, both of which have double dashes in their name "Table--1" (Received from a share, not my naming convention ;) )
The SQL query sent here is malformed due to this, as it cannot use the table name to find any of the tables columns: https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/union.sql#L89

### Steps to reproduce
Just try to union two tables with double dashes in their names. I would hazard a guess that other special characters also cause the code to break

### Expected results
The two tables to union

### Actual results
The query linked in the above code snippet creates malformed SQL like below. NOTE: no columns have been added due to not being retrievable due to the table name.
    create or replace  table TARGET_DB.SCHEMA.UNIONED_TABLE  as
(
select
    cast('DB.SCHEMA.TABLE--X--1' as varchar) as _dbt_source_relation,
from DB.SCHEMA.TABLE--X--1
);

### Screenshots and log output
N/A

### System information
---
packages:
  - local: /libs/dbt-utils-0.7.6
  - local: /libs/dbt-utils-0.7.6-custom

**Which database are you using dbt with?**
- snowflake

**The output of `dbt --version`:**
```
installed version: 1.0.8
   latest version: unknown

The latest version of dbt could not be determined!
Make sure that the following URL is accessible:
https://pypi.org/pypi/dbt-core/json

Plugins:
  - bigquery: 1.0.0 - No PYPI version available
  - postgres: 1.0.8 - Up to date!
  - redshift: 1.0.1 - No PYPI version available
  - snowflake: 1.0.1 - No PYPI version available
```

### Additional context
I have implemented a fix locally that saves the tables I am unioning with double quotes 

editing this line: https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/get_relations_by_pattern.sql#L21

to this:       identifier='"' ~ row.table_name ~ '"',

### Are you interested in contributing the fix?
My fix is above :)

**Comment by joellabes** [comment]
That's an interesting one, thanks @CharlieJ20! I would be wary to make the change you propose without knowing that it doesn't break normally-named tables - my spidey senses start tingling any time we're getting into obscure quoting logic. In any case we'd want to use `adapter.quote` because bigquery uses backticks for identifiers, and even then your change only handles strangely named tables (what about schemas etc?)

All of this to say that while I agree that you've found some undesirable behaviour, I don't want to add complexity to the default path without remaining confident that everything keeps working. In the meantime your custom override of the macro might be the safest bet.
