### ISSUE TITLE
Surrogate key relies on deprecated hash macro 

### ISSUE THREAD

**Issue by korompaiistvan** [dbt-labs/dbt-utils#666]
Hi,

While looking at the implementation detail of the surrogate key macro, I noticed that it seems to rely on the hash macro which I understand to be deprecated since it is in the deprecated folder (macros/cross_db_utils/deprecated/hash.sql).

Yet the surrogate key macro relies on it on line 49. [See line here](https://github.com/dbt-labs/dbt-utils/blob/fc8b083f07b72790234f3227df40c4f54dd60c38/macros/sql/surrogate_key.sql#L49)

I am not sure if this is an outright issue, but it is confusing while browsing and discovering the codebase.

Thank you very much for the great project.

**Comment by joellabes** [comment]
Hey @korompaiistvan, this is a good callout! 

The macro is actually using the version [built into dbt Core](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#hash) - this is the reason that the dbt_utils version is deprecated. 

You can tell that `hash()` isn't a dbt_utils macro because it doesn't have the `dbt_utils.` namespace at the start. Technically, it could be either `dbt.hash()` or just `hash()` - we chose to not have any namespace but that could be confusing and we might need to reconsider. What do you think?
