### ISSUE TITLE
Add option to ignore columns in `equality` test

### ISSUE THREAD

**Issue by brunocostalopes** [dbt-labs/dbt-utils#734]
### Describe the feature

I would like to be able to specify a list of columns to exclude on an `equality` test.

### Describe alternatives you've considered

We can of course use `compare_columns` to list all columns, except the ones we want to exclude, but this leads to large yml files, difficult to maintain as our models evolve.

### Additional context

Not database specific, it can be implemented across all different databases.

### Who will this benefit?

This feature would be great for anyone who wants to compare data across environments where, for example, some of the fields are masked in one of the environments.
Another scenario where this can be useful is when updating the logic on a small subset of fields in a model and wanting to compare the development model with the production one, but obviously excluding the updated fields (which are expected to be different)

### Are you interested in contributing this feature?
I have implemented this locally already. Happy to raise a PR if people think this feature is helpful.

**Comment by joellabes** [comment]
@brunocostalopes thanks for this! I am very on board with this as an idea. 

Some implementation notes:
- The new argument should be `ignore_columns` (as opposed to `exclude`; let me know if you have a different opinion)
- If both `compare_columns` and `ignore_columns` are provided, it should throw an error (see how [`union_relations`](https://github.com/dbt-labs/dbt-utils/blob/84cf0f2971f5bf539b06c42373a5e80b59ba7047/macros/sql/union.sql#L7-L9) does it)
- Please also add some integration tests which exercise the ~new~ behaviour. I went looking for the existing integration tests for this test and didn't find any, so instead here's an [example from the recency test](https://github.com/dbt-labs/dbt-utils/blob/main/integration_tests/models/generic_tests/schema.yml#L146-L176). Note in particular that you can check that the test catches failing records by setting error_if to `<1`. 

Since it's your issue and you've got the code already to hand, you get first dibs on implementing it, but if you're not going to have time to do the other things then it looks like @deanna-minnick is also willing to lend a hand - just let us know on the issue thread. 

Let me know if you run into any issues 🎉

**Comment by brunocostalopes** [comment]
@joellabes sounds good, thank you for the implementation notes. I'll take a first stab at it and if it seems like I'm stuck I'll ask @deanna-minnick for a bit of help.

**Comment by brunocostalopes** [comment]
@joellabes I've raised the PR.

Please feel free to comment and suggest any changes, particularly if you have any suggestions on how to compare the list of columns in the ignore list with the list returned by the adapter (feels a bit hacky with the lowercase and the trim but couldn't think of a better approach so maybe I'm just missing something).
