### ISSUE TITLE
equal_rowcount, fewer_rows_than macros don't work on Trino due to lateral column aliasing

### ISSUE THREAD

**Issue by damian3031** [dbt-labs/dbt-utils#744]
### Describe the bug
Current implementations of [fewer_rows_than](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/fewer_rows_than.sql) and [equal_rowcount](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equal_rowcount.sql) are not working on warehouses which do not support lateral column aliasing.

### Steps to reproduce
Use test `fewer_rows_than` or `equal_rowcount` on warehouse which do not support lateral column aliasing.

### Expected results
Test is working.

### Actual results
Receiving error `Column 'id_dbtutils_test_equal_rowcount' cannot be resolved`

**Which database are you using dbt with?**
Trino, but relevant to all warehouses which do not support lateral column aliasing

**The output of `dbt --version`:**
1.3.0

### Additional context
In [equal_rowcount](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equal_rowcount.sql) macro, at line [35](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equal_rowcount.sql#L35) column alias is created, which is later used in [group by](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equal_rowcount.sql#L49) clause within same query. It won't work on warehouses which do not support lateral column aliasing.
We could change this `group by` and instead of [specifying column names](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/equal_rowcount.sql#L29), we could pass column indexes, sth like `group by 1, 2, 3`. It will work then on warehouses which do not support lateral column aliasing. In addition, this style is recommended on dbt blog: https://www.getdbt.com/blog/write-better-sql-a-defense-of-group-by-1/

### Are you interested in contributing the fix?
Yes, I have already prepared solution working on warehouses which do not support lateral column aliasing.

**Comment by joellabes** [comment]
@damian3031 thanks for opening this! 

Amusingly (?), in some cases T-SQL _doesn't_ support `group by n` syntax which is the reason that these tests behave the way they do. Changing back to `group by 1, 2, 3` will solve your problem, but go back to breaking tsql. You can read more about this here for example: https://github.com/dbt-labs/dbt-utils/pull/310

Officially, dbt utils only commits to supporting the dbt Labs-maintained adapters, but we have historically been open to making changes that support other adapters as long as they don't impact the main mission. 

Now that we have two community-powered adapters whose needs are in conflict, I think that some combination of @dbeatty10, @dataders, maybe @Fleid and I will need to put our heads together and think about what a broader multi-adapter strategy on dbt utils looks like. 

I doubt that we'll move this forward before the holiday break, but it's on my list for the new year!

**Comment by dataders** [comment]
@damian3031 really appreciate putting the whole story together here.

More context is that @damian3031 is the maintainer of [`dbt-utils-trino`](https://github.com/starburstdata/dbt-trino-utils) in which `equal_rowcount` & `fewer_rows_than` have been completely overriden just because of the lateral aliasiing issue. However, I do agree that the default groupby clause implementation could be improved. I like the intent behind #746 if wrapping the groupby-clause generation into it's own dispatchable macro, and that `dbt_utils.group_by` is the natural macro to use. However, like @joellabes said, you can't group by column order references in TSQL (bc TIL lateral aliasing isn't possible in TSQL due to its [All-at-Once operation model](https://social.technet.microsoft.com/wiki/contents/articles/20724.all-at-once-operations-in-t-sql.aspx)).

These test macros were working for TSQL and tsql-utils when I made them but:
1. We didn't keep up with maintenance and updating versions for tsql-utils
2. #633 (re-implemented later by joel for some reason in https://github.com/dbt-labs/dbt-utils/commit/78afeddc6bde120f776fbafeee6f04f854b302a3 broke compatibility with tsql-utils, and,
3. because this repo doesn't test for compatibility with it's corresponding shim packages, this breaking change went unnoticed.

Proposal:

- [ ] we take the approach of #746, but first perhaps extend `dbt_utils.group_by` to allow for group by clauses with actual column names/references.
- [ ] discuss with core adapters eng team as this issue has also recently come up with dbt-core and adapters (around support for python 3.11 as part of dbt-core's 1.4 release) due to a lack of test coverage

:eyes: @sdebruyn @b-per @prdpsvs

**Comment by joellabes** [comment]
> first perhaps extend `dbt_utils.group_by` to allow for group by clauses with actual column names/references.

I don't think I'm into this - feels like a massive overloading of the macro. To maintain backwards compatibility it would have to be something like:

```sql
{% macro group_by(groupings) %}
  {% if groupings is list %}
    group by {{ groupings | join(", ")
  {% else %}
    group by {{ range(1, groupings) | join(", ") }} /* I don't think this is the correct syntax, doesn't really matter*/
  {% endif %}
{% endmacro %}
```

Which would mean that all existing places where the macro is used still wouldn't work. And in any case there are also a lot of places where needing to know the specific column names is undesirable (e.g. I have done `{{ dbt_utils.group_by(4 if something else 5) }}`)

**Comment by RobbertDM** [comment]
We also ran into this issue today. Maybe we can solve this by adding a shim in https://github.com/starburstdata/dbt-trino  ?

**Comment by dbeatty10** [comment]
@RobbertDM Are you already installing and using the [trino_utils](https://hub.getdbt.com/starburstdata/trino_utils/latest/) package?

https://github.com/starburstdata/dbt-trino-utils/commit/7ac7c8b2ef50fc1b86a70eeb82044d3b04313c6e is where `equal_rowcount` & `fewer_rows_than` were completely overridden because of the lateral aliasing issue.

**Comment by RobbertDM** [comment]
Ah yes, thank you!
