### ISSUE TITLE
Expand dbt_utils.equal_rowcount to test the equality between the rowcount of the model and the sum of rowcounts of several models 

### ISSUE THREAD

**Issue by moreaupascal56** [dbt-labs/dbt-utils#758]
### Describe the feature

Hello :) 

We had the need to use the `equal_rowcount` test in a model that does an UNION ALL of several models. 
So we needed to test that: 

`rowcount(modelA) = rowcount(modelB) + rowcount(modelC) + ... + rowcount(modelN)
`

example: 

if modelA is: 
```
select * from modelB
UNION ALL 
select * from modelC
```

it makes sense to have such a test.

We forked the test from dbt_utils in our repo to allow this behaviour but if you think it can be useful to other I'll be happy to contribute this to the repo. 

### Additional context

it will need care to make it backward compatible

### Who will this benefit?
Anyone that want to test the equality of row counts between several models 
### Are you interested in contributing this feature?

sure

**Comment by joellabes** [comment]
Hey @moreaupascal56, thanks for opening this! I can see why you'd need to run this test. I don't think it makes sense as an addon to the existing test, because as you note it would be complex to keep its behaviour compatible while staying friendly. 

In the meantime, perhaps you'd like to share an example of what you've made on the community forum: https://discourse.getdbt.com/c/show-and-tell/22

If there's a lot of interest there (or as comments on this issue), I'd be happy to review adding it in as a totally new test. Right now it feels like a bit of an edge case to me though
