### ISSUE TITLE
Resolve support for Materialized views on databricks in dbt_utils.get_table_types_sql 

### ISSUE THREAD

**Issue by SLe-Corre** [dbt-labs/dbt-utils#881]
### Describe the bug
Databricks have recently updated their information schema standards to standardize table types for materialized views and streaming tables.
This means the macro "Get_table_types_sql" and specifically the "databricks__get_table_types_sql()" part needs to reflect the move to `MATERIALIZED_VIEW` as opposed to `MATERIALIZED VIEW` as current.

Running the macro currently, or calling something like generate_sources from dbt_codegen which depends on this will return the error:
Runtime Error
  Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'materialized_view'

when trying to read from a schema containing a materialized table.

### Steps to reproduce
On databricks, have a schema containing a materialized view.
call the codegen macro  `codegen.generate_source()` or directly call the dbt utils get table types against this schema.

### Expected results

Code runs without error.

### Actual results

Code returns:
Runtime Error
  Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'materialized_view'

### Screenshots and log output

This is the code that gets generated, and successfully run against the warehouse. I've highlighted in yellow how materialized_view is falling under the else condition rather than the catchment case above it.

<img width="500" alt="image" src="https://github.com/dbt-labs/dbt-utils/assets/32954229/1c4fbdb7-bfde-470b-b19b-b9ce445b7c46">

### System information

packages:
  - package: dbt-labs/codegen
    version: 0.12.1 ## update to latest version here

  - package: dbt-labs/dbt_utils
    version: 1.1.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: Databricks)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.11
  - latest:    1.7.11 - Up to date!

Plugins:
  - spark:      1.7.1  - Up to date!
  - databricks: 1.7.13 - Up to date!
```

### Additional context

This can be fixed by changing the line:
https://github.com/dbt-labs/dbt-utils/blob/951d087821fb4b07255cd74891ffe5b21e19a3ed/macros/sql/get_table_types_sql.sql#L29C1-L29C65

from `MATERIALIZED VIEW` to `MATERIALIZED_VIEW`

### Are you interested in contributing the fix?

Should be enough detail to fix above, I wouldn't know how to get started contributing.

**Comment by federicolavatori-bynder** [comment]
In Snowflake I have a very similar error when calling the codegen macro `codegen.generate_source()` against a schema with materialialized views:

```
Encountered an error while running operation: Runtime Error
Field "type" of type Optional[SnowflakeRelationType] in SnowflakeRelation has invalid value 'materializedview’
```

Output of the invocation is almost empty

**Comment by davehowell** [comment]
@federicolavatori-bynder I can't currently test on Snowflake but I am having a very similar error on BigQuery and I have a temporary workaround that might work for you. 

In your project dir, create a file under `macros` dir called `get_table_types_sql.sql`

Put this in the file:

```sql
{% macro snowflake__get_table_types_sql() %}
            case table_type
                when 'BASE TABLE' then 'table'
                when 'CLONE' then 'table'
                when 'EXTERNAL TABLE' then 'external'
                when 'MATERIALIZED VIEW' then 'materialized_view'
                else lower(table_type)
            end as {{ adapter.quote('table_type') }}
{% endmacro %}
```

Then try the macro to see if it fixes it.
e.g. something like this
```sh
dbt run-operation generate_source --args '{"table_pattern": "%_something"}'
```

n.b. You can override macros in packages with your own in that directory if you give it the same name. 

I think that the fix is just the `'materialized_view'` instead of `'materializedview'`  based on the RelationType https://github.com/dbt-labs/dbt-adapters/blob/e966f0ddea91ae531d92e703696bb80144e5b28e/dbt-adapters/src/dbt/adapters/contracts/relation.py#L20 


Although ... maybe materialized views are not supported for Snowflake at all based on this: https://github.com/dbt-labs/dbt-adapters/blob/e966f0ddea91ae531d92e703696bb80144e5b28e/dbt-snowflake/src/dbt/adapters/snowflake/relation_configs/policies.py#L7

And this comment here https://github.com/dbt-labs/dbt-adapters/blob/e966f0ddea91ae531d92e703696bb80144e5b28e/dbt-snowflake/src/dbt/adapters/snowflake/impl.py#L239 
A pity. My workaround probably doesn't work for you.

Looks like they do support dynamic tables and external tables though.
